# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  gen-openapi:
    desc: | 
      Generate the (shared) OpenAPI file from the documentation folder.
    cmds:
      - mkdir -p api/gen/8.6-beta
      - | 
        yq-v4.43.1 eval-all \
          '. as $item ireduce ({}; . * $item )' \
          camera/documentation/bmcc6kpro/8.6-beta/swagger/**/* \
          > api/gen/8.6-beta/openapi.yaml
